package com.github.kaydogz.daboismod.client.model;

import com.github.kaydogz.daboismod.entity.WerewolfEntity;
import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.Model;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.util.math.MathHelper;

/**
 * This model class and the texture was originally made by Dr. Zhark for his Mo' Creatures Mod. I updated the model file to 1.15.2.
 * @author Dr. Zhark && mrkdo
 *
 */
public class WerewolfModel extends EntityModel<WerewolfEntity> {
    ModelRenderer head;
    ModelRenderer nose;
    ModelRenderer snout;
    ModelRenderer teethUpper;
    ModelRenderer teethLower;
    ModelRenderer mouth;
    ModelRenderer leftEar;
    ModelRenderer rightEar;
    ModelRenderer neckA;
    ModelRenderer neckB;
    ModelRenderer leftSideburn;
    ModelRenderer rightSideburn;
    ModelRenderer chest;
    ModelRenderer abdomen;
    ModelRenderer tailA;
    ModelRenderer tailB;
    ModelRenderer tailC;
    ModelRenderer tailD;
    ModelRenderer rightLegA;
    ModelRenderer rightLegB;
    ModelRenderer rightLegC;
    ModelRenderer rightFoot;
    ModelRenderer leftLegA;
    ModelRenderer leftLegB;
    ModelRenderer leftLegC;
    ModelRenderer leftFoot;
    ModelRenderer rightArmA;
    ModelRenderer rightArmB;
    ModelRenderer rightArmC;
    ModelRenderer rightHand;
    ModelRenderer leftArmA;
    ModelRenderer leftArmB;
    ModelRenderer leftArmC;
    ModelRenderer leftHand;
    ModelRenderer rightFinger1;
    ModelRenderer rightFinger2;
    ModelRenderer rightFinger3;
    ModelRenderer rightFinger4;
    ModelRenderer rightFinger5;
    ModelRenderer leftFinger1;
    ModelRenderer leftFinger2;
    ModelRenderer leftFinger3;
    ModelRenderer leftFinger4;
    ModelRenderer leftFinger5;
    public boolean hunched;
    
    public WerewolfModel() {
        this.createParts();
    }

    private void createParts() {
        this.textureWidth = 64;
        this.textureHeight = 128;
        (this.head = new ModelRenderer((Model) this, 0, 0)).addBox(-4.0f, -3.0f, -6.0f, 8, 8, 6);
        this.head.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.head.setTextureSize(64, 128);
        (this.nose = new ModelRenderer((Model) this, 44, 33)).addBox(-1.5f, -1.7f, -12.3f, 3, 2, 7);
        this.nose.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.nose, 0.2792527f, 0.0f, 0.0f);
        (this.snout = new ModelRenderer((Model) this, 0, 25)).addBox(-2.0f, 2.0f, -12.0f, 4, 2, 6);
        this.snout.setRotationPoint(0.0f, -8.0f, -6.0f);
        (this.teethUpper = new ModelRenderer((Model) this, 46, 18)).addBox(-2.0f, 4.01f, -12.0f, 4, 2, 5);
        this.teethUpper.setRotationPoint(0.0f, -8.0f, -6.0f);
        (this.teethLower = new ModelRenderer((Model) this, 20, 109)).addBox(-1.5f, -12.5f, 2.01f, 3, 5, 2);
        this.teethLower.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.teethLower, 2.530727f, 0.0f, 0.0f);
        (this.mouth = new ModelRenderer((Model) this, 42, 69)).addBox(-1.5f, -12.5f, 0.0f, 3, 9, 2);
        this.mouth.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.mouth, 2.530727f, 0.0f, 0.0f);
        (this.leftEar = new ModelRenderer((Model) this, 13, 14)).addBox(0.5f, -7.5f, -1.0f, 3, 5, 1);
        this.leftEar.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.leftEar, 0.0f, 0.0f, 0.1745329f);
        (this.rightEar = new ModelRenderer((Model) this, 22, 0)).addBox(-3.5f, -7.5f, -1.0f, 3, 5, 1);
        this.rightEar.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.rightEar, 0.0f, 0.0f, -0.1745329f);
        (this.neckA = new ModelRenderer((Model) this, 28, 0)).addBox(-3.5f, -3.0f, -7.0f, 7, 8, 7);
        this.neckA.setRotationPoint(0.0f, -5.0f, -2.0f);
        this.setRotation(this.neckA, -0.6025001f, 0.0f, 0.0f);
        (this.neckB = new ModelRenderer((Model) this, 0, 14)).addBox(-1.5f, -2.0f, -5.0f, 3, 4, 7);
        this.neckB.setRotationPoint(0.0f, -1.0f, -6.0f);
        this.setRotation(this.neckB, -0.4537856f, 0.0f, 0.0f);
        (this.leftSideburn = new ModelRenderer((Model) this, 28, 33)).addBox(3.0f, 0.0f, -2.0f, 2, 6, 6);
        this.leftSideburn.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.leftSideburn, -0.2094395f, 0.418879f, -0.0872665f);
        (this.rightSideburn = new ModelRenderer((Model) this, 28, 45)).addBox(-5.0f, 0.0f, -2.0f, 2, 6, 6);
        this.rightSideburn.setRotationPoint(0.0f, -8.0f, -6.0f);
        this.setRotation(this.rightSideburn, -0.2094395f, -0.418879f, 0.0872665f);
        (this.chest = new ModelRenderer((Model) this, 20, 15)).addBox(-4.0f, 0.0f, -7.0f, 8, 8, 10);
        this.chest.setRotationPoint(0.0f, -6.0f, -2.5f);
        this.setRotation(this.chest, 0.641331f, 0.0f, 0.0f);
        (this.abdomen = new ModelRenderer((Model) this, 0, 40)).addBox(-3.0f, -8.0f, -8.0f, 6, 14, 8);
        this.abdomen.setRotationPoint(0.0f, 4.5f, 5.0f);
        this.setRotation(this.abdomen, 0.2695449f, 0.0f, 0.0f);
        (this.tailA = new ModelRenderer((Model) this, 52, 42)).addBox(-1.5f, -1.0f, -2.0f, 3, 4, 3);
        this.tailA.setRotationPoint(0.0f, 9.5f, 6.0f);
        this.setRotation(this.tailA, 1.064651f, 0.0f, 0.0f);
        (this.tailC = new ModelRenderer((Model) this, 48, 59)).addBox(-2.0f, 6.8f, -4.6f, 4, 6, 4);
        this.tailC.setRotationPoint(0.0f, 9.5f, 6.0f);
        this.setRotation(this.tailC, 1.099557f, 0.0f, 0.0f);
        (this.tailB = new ModelRenderer((Model) this, 48, 49)).addBox(-2.0f, 2.0f, -2.0f, 4, 6, 4);
        this.tailB.setRotationPoint(0.0f, 9.5f, 6.0f);
        this.setRotation(this.tailB, 0.7504916f, 0.0f, 0.0f);
        (this.tailD = new ModelRenderer((Model) this, 52, 69)).addBox(-1.5f, 9.8f, -4.1f, 3, 5, 3);
        this.tailD.setRotationPoint(0.0f, 9.5f, 6.0f);
        this.setRotation(this.tailD, 1.099557f, 0.0f, 0.0f);
        (this.rightLegA = new ModelRenderer((Model) this, 12, 64)).addBox(-2.5f, -1.5f, -3.5f, 3, 8, 5);
        this.rightLegA.setRotationPoint(-3.0f, 9.5f, 3.0f);
        this.setRotation(this.rightLegA, -0.8126625f, 0.0f, 0.0f);
        (this.rightFoot = new ModelRenderer((Model) this, 14, 93)).addBox(-2.506667f, 12.5f, -5.0f, 3, 2, 3);
        this.rightFoot.setRotationPoint(-3.0f, 9.5f, 3.0f);
        (this.rightLegB = new ModelRenderer((Model) this, 14, 76)).addBox(-1.9f, 4.2f, 0.5f, 2, 2, 5);
        this.rightLegB.setRotationPoint(-3.0f, 9.5f, 3.0f);
        this.setRotation(this.rightLegB, -0.8445741f, 0.0f, 0.0f);
        (this.rightLegC = new ModelRenderer((Model) this, 14, 83)).addBox(-2.0f, 6.2f, 0.5f, 2, 8, 2);
        this.rightLegC.setRotationPoint(-3.0f, 9.5f, 3.0f);
        this.setRotation(this.rightLegC, -0.2860688f, 0.0f, 0.0f);
        (this.leftLegB = new ModelRenderer((Model) this, 0, 76)).addBox(-0.1f, 4.2f, 0.5f, 2, 2, 5);
        this.leftLegB.setRotationPoint(3.0f, 9.5f, 3.0f);
        this.setRotation(this.leftLegB, -0.8445741f, 0.0f, 0.0f);
        (this.leftFoot = new ModelRenderer((Model) this, 0, 93)).addBox(-0.5066667f, 12.5f, -5.0f, 3, 2, 3);
        this.leftFoot.setRotationPoint(3.0f, 9.5f, 3.0f);
        (this.leftLegC = new ModelRenderer((Model) this, 0, 83)).addBox(0.0f, 6.2f, 0.5f, 2, 8, 2);
        this.leftLegC.setRotationPoint(3.0f, 9.5f, 3.0f);
        this.setRotation(this.leftLegC, -0.2860688f, 0.0f, 0.0f);
        (this.leftLegA = new ModelRenderer((Model) this, 0, 64)).addBox(-0.5f, -1.5f, -3.5f, 3, 8, 5);
        this.leftLegA.setRotationPoint(3.0f, 9.5f, 3.0f);
        this.setRotation(this.leftLegA, -0.8126625f, 0.0f, 0.0f);
        (this.rightArmB = new ModelRenderer((Model) this, 48, 77)).addBox(-3.5f, 1.0f, -1.5f, 4, 8, 4);
        this.rightArmB.setRotationPoint(-4.0f, -4.0f, -2.0f);
        this.setRotation(this.rightArmB, 0.2617994f, 0.0f, 0.3490659f);
        (this.rightArmC = new ModelRenderer((Model) this, 48, 112)).addBox(-6.0f, 5.0f, 3.0f, 4, 7, 4);
        this.rightArmC.setRotationPoint(-4.0f, -4.0f, -2.0f);
        this.setRotation(this.rightArmC, -0.3490659f, 0.0f, 0.0f);
        (this.leftArmB = new ModelRenderer((Model) this, 48, 89)).addBox(-0.5f, 1.0f, -1.5f, 4, 8, 4);
        this.leftArmB.setRotationPoint(4.0f, -4.0f, -2.0f);
        this.setRotation(this.leftArmB, 0.2617994f, 0.0f, -0.3490659f);
        (this.rightHand = new ModelRenderer((Model) this, 32, 118)).addBox(-6.0f, 12.5f, -1.5f, 4, 3, 4);
        this.rightHand.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.rightArmA = new ModelRenderer((Model) this, 0, 108)).addBox(-5.0f, -3.0f, -2.0f, 5, 5, 5);
        this.rightArmA.setRotationPoint(-4.0f, -4.0f, -2.0f);
        this.setRotation(this.rightArmA, 0.6320364f, 0.0f, 0.0f);
        (this.leftArmA = new ModelRenderer((Model) this, 0, 98)).addBox(0.0f, -3.0f, -2.0f, 5, 5, 5);
        this.leftArmA.setRotationPoint(4.0f, -4.0f, -2.0f);
        this.setRotation(this.leftArmA, 0.6320364f, 0.0f, 0.0f);
        (this.leftArmC = new ModelRenderer((Model) this, 48, 101)).addBox(2.0f, 5.0f, 3.0f, 4, 7, 4);
        this.leftArmC.setRotationPoint(4.0f, -4.0f, -2.0f);
        this.setRotation(this.leftArmC, -0.3490659f, 0.0f, 0.0f);
        (this.leftHand = new ModelRenderer((Model) this, 32, 111)).addBox(2.0f, 12.5f, -1.5f, 4, 3, 4);
        this.leftHand.setRotationPoint(4.0f, -4.0f, -2.0f);
        (this.rightFinger1 = new ModelRenderer((Model) this, 8, 120)).addBox(-0.5f, 0.0f, -0.5f, 1, 3, 1);
        this.rightFinger1.setRotationPoint(-6.5f, 11.5f, -0.5f);
        (this.rightFinger1 = new ModelRenderer((Model) this, 8, 120)).addBox(-3.0f, 15.5f, 1.0f, 1, 3, 1);
        this.rightFinger1.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.rightFinger2 = new ModelRenderer((Model) this, 12, 124)).addBox(-3.5f, 15.5f, -1.5f, 1, 3, 1);
        this.rightFinger2.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.rightFinger3 = new ModelRenderer((Model) this, 12, 119)).addBox(-4.8f, 15.5f, -1.5f, 1, 4, 1);
        this.rightFinger3.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.rightFinger4 = new ModelRenderer((Model) this, 16, 119)).addBox(-6.0f, 15.5f, -0.5f, 1, 4, 1);
        this.rightFinger4.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.rightFinger5 = new ModelRenderer((Model) this, 16, 124)).addBox(-6.0f, 15.5f, 1.0f, 1, 3, 1);
        this.rightFinger5.setRotationPoint(-4.0f, -4.0f, -2.0f);
        (this.leftFinger1 = new ModelRenderer((Model) this, 8, 124)).addBox(2.0f, 15.5f, 1.0f, 1, 3, 1);
        this.leftFinger1.setRotationPoint(4.0f, -4.0f, -2.0f);
        (this.leftFinger2 = new ModelRenderer((Model) this, 0, 124)).addBox(2.5f, 15.5f, -1.5f, 1, 3, 1);
        this.leftFinger2.setRotationPoint(4.0f, -4.0f, -2.0f);
        (this.leftFinger3 = new ModelRenderer((Model) this, 0, 119)).addBox(3.8f, 15.5f, -1.5f, 1, 4, 1);
        this.leftFinger3.setRotationPoint(4.0f, -4.0f, -2.0f);
        (this.leftFinger4 = new ModelRenderer((Model) this, 4, 119)).addBox(5.0f, 15.5f, -0.5f, 1, 4, 1);
        this.leftFinger4.setRotationPoint(4.0f, -4.0f, -2.0f);
        (this.leftFinger5 = new ModelRenderer((Model) this, 4, 124)).addBox(5.0f, 15.5f, 1.0f, 1, 3, 1);
        this.leftFinger5.setRotationPoint(4.0f, -4.0f, -2.0f);
    }
    
    @Override
    public void render(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn, float red, float green, float blue, float alpha) {
    	this.head.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.nose.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.snout.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.teethUpper.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.teethLower.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.mouth.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftEar.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightEar.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.neckA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.neckB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftSideburn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightSideburn.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.chest.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.abdomen.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.tailA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.tailC.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.tailB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.tailD.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightLegA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightLegB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightLegC.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftLegB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFoot.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftLegC.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftLegA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightArmB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightArmC.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftArmB.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightHand.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightArmA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftArmA.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftArmC.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftHand.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFinger1.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFinger2.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFinger3.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFinger4.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.rightFinger5.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFinger1.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFinger2.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFinger3.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFinger4.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        this.leftFinger5.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
    }
    
    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
    @Override
    public void setRotationAngles(WerewolfEntity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
    	final float radianF = 57.29578f;
        final float RLegXRot = MathHelper.cos((float) (limbSwing * 0.6662f + Math.PI)) * 0.8f * limbSwingAmount;
        final float LLegXRot = MathHelper.cos(limbSwing * 0.6662f) * 0.8f * limbSwingAmount;
        this.head.rotateAngleY = netHeadYaw / radianF;
        if (!this.hunched) {
            this.head.rotationPointY = -8.0f;
            this.head.rotationPointZ = -6.0f;
            this.head.rotateAngleX = headPitch / radianF;
            this.neckA.rotateAngleX = -34.0f / radianF;
            this.neckA.rotationPointY = -5.0f;
            this.neckA.rotationPointZ = -2.0f;
            this.neckB.rotationPointY = -1.0f;
            this.neckB.rotationPointZ = -6.0f;
            this.chest.rotationPointY = -6.0f;
            this.chest.rotationPointZ = -2.5f;
            this.chest.rotateAngleX = 36.0f / radianF;
            this.abdomen.rotateAngleX = 15.0f / radianF;
            this.leftLegA.rotationPointZ = 3.0f;
            this.leftArmA.rotationPointY = -4.0f;
            this.leftArmA.rotationPointZ = -2.0f;
            this.tailA.rotationPointY = 9.5f;
            this.tailA.rotationPointZ = 6.0f;
        }
        else {
            this.head.rotationPointY = 0.0f;
            this.head.rotationPointZ = -11.0f;
            this.head.rotateAngleX = (15.0f + headPitch) / radianF;
            this.neckA.rotateAngleX = -10.0f / radianF;
            this.neckA.rotationPointY = 2.0f;
            this.neckA.rotationPointZ = -6.0f;
            this.neckB.rotationPointY = 9.0f;
            this.neckB.rotationPointZ = -9.0f;
            this.chest.rotationPointY = 1.0f;
            this.chest.rotationPointZ = -7.5f;
            this.chest.rotateAngleX = 60.0f / radianF;
            this.abdomen.rotateAngleX = 75.0f / radianF;
            this.leftLegA.rotationPointZ = 7.0f;
            this.leftArmA.rotationPointY = 4.5f;
            this.leftArmA.rotationPointZ = -6.0f;
            this.tailA.rotationPointY = 7.5f;
            this.tailA.rotationPointZ = 10.0f;
        }
        this.nose.rotationPointY = this.head.rotationPointY;
        this.snout.rotationPointY = this.head.rotationPointY;
        this.teethUpper.rotationPointY = this.head.rotationPointY;
        this.leftEar.rotationPointY = this.head.rotationPointY;
        this.rightEar.rotationPointY = this.head.rotationPointY;
        this.teethLower.rotationPointY = this.head.rotationPointY;
        this.mouth.rotationPointY = this.head.rotationPointY;
        this.leftSideburn.rotationPointY = this.head.rotationPointY;
        this.rightSideburn.rotationPointY = this.head.rotationPointY;
        this.nose.rotationPointZ = this.head.rotationPointZ;
        this.snout.rotationPointZ = this.head.rotationPointZ;
        this.teethUpper.rotationPointZ = this.head.rotationPointZ;
        this.leftEar.rotationPointZ = this.head.rotationPointZ;
        this.rightEar.rotationPointZ = this.head.rotationPointZ;
        this.teethLower.rotationPointZ = this.head.rotationPointZ;
        this.mouth.rotationPointZ = this.head.rotationPointZ;
        this.leftSideburn.rotationPointZ = this.head.rotationPointZ;
        this.rightSideburn.rotationPointZ = this.head.rotationPointZ;
        this.leftArmB.rotationPointY = this.leftArmA.rotationPointY;
        this.leftArmC.rotationPointY = this.leftArmA.rotationPointY;
        this.leftHand.rotationPointY = this.leftArmA.rotationPointY;
        this.leftFinger1.rotationPointY = this.leftArmA.rotationPointY;
        this.leftFinger2.rotationPointY = this.leftArmA.rotationPointY;
        this.leftFinger3.rotationPointY = this.leftArmA.rotationPointY;
        this.leftFinger4.rotationPointY = this.leftArmA.rotationPointY;
        this.leftFinger5.rotationPointY = this.leftArmA.rotationPointY;
        this.rightArmA.rotationPointY = this.leftArmA.rotationPointY;
        this.rightArmB.rotationPointY = this.leftArmA.rotationPointY;
        this.rightArmC.rotationPointY = this.leftArmA.rotationPointY;
        this.rightHand.rotationPointY = this.leftArmA.rotationPointY;
        this.rightFinger1.rotationPointY = this.leftArmA.rotationPointY;
        this.rightFinger2.rotationPointY = this.leftArmA.rotationPointY;
        this.rightFinger3.rotationPointY = this.leftArmA.rotationPointY;
        this.rightFinger4.rotationPointY = this.leftArmA.rotationPointY;
        this.rightFinger5.rotationPointY = this.leftArmA.rotationPointY;
        this.leftArmB.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftArmC.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftHand.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftFinger1.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftFinger2.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftFinger3.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftFinger4.rotationPointZ = this.leftArmA.rotationPointZ;
        this.leftFinger5.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightArmA.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightArmB.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightArmC.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightHand.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightFinger1.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightFinger2.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightFinger3.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightFinger4.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightFinger5.rotationPointZ = this.leftArmA.rotationPointZ;
        this.rightLegA.rotationPointZ = this.leftLegA.rotationPointZ;
        this.rightLegB.rotationPointZ = this.leftLegA.rotationPointZ;
        this.rightLegC.rotationPointZ = this.leftLegA.rotationPointZ;
        this.rightFoot.rotationPointZ = this.leftLegA.rotationPointZ;
        this.leftLegB.rotationPointZ = this.leftLegA.rotationPointZ;
        this.leftLegC.rotationPointZ = this.leftLegA.rotationPointZ;
        this.leftFoot.rotationPointZ = this.leftLegA.rotationPointZ;
        this.tailB.rotationPointY = this.tailA.rotationPointY;
        this.tailB.rotationPointZ = this.tailA.rotationPointZ;
        this.tailC.rotationPointY = this.tailA.rotationPointY;
        this.tailC.rotationPointZ = this.tailA.rotationPointZ;
        this.tailD.rotationPointY = this.tailA.rotationPointY;
        this.tailD.rotationPointZ = this.tailA.rotationPointZ;
        this.nose.rotateAngleY = this.head.rotateAngleY;
        this.snout.rotateAngleY = this.head.rotateAngleY;
        this.teethUpper.rotateAngleY = this.head.rotateAngleY;
        this.leftEar.rotateAngleY = this.head.rotateAngleY;
        this.rightEar.rotateAngleY = this.head.rotateAngleY;
        this.teethLower.rotateAngleY = this.head.rotateAngleY;
        this.mouth.rotateAngleY = this.head.rotateAngleY;
        this.teethLower.rotateAngleX = this.head.rotateAngleX + 2.530727f;
        this.mouth.rotateAngleX = this.head.rotateAngleX + 2.530727f;
        this.leftSideburn.rotateAngleX = -0.2094395f + this.head.rotateAngleX;
        this.leftSideburn.rotateAngleY = 0.418879f + this.head.rotateAngleY;
        this.rightSideburn.rotateAngleX = -0.2094395f + this.head.rotateAngleX;
        this.rightSideburn.rotateAngleY = -0.418879f + this.head.rotateAngleY;
        this.nose.rotateAngleX = 0.2792527f + this.head.rotateAngleX;
        this.snout.rotateAngleX = this.head.rotateAngleX;
        this.teethUpper.rotateAngleX = this.head.rotateAngleX;
        this.leftEar.rotateAngleX = this.head.rotateAngleX;
        this.rightEar.rotateAngleX = this.head.rotateAngleX;
        this.rightLegA.rotateAngleX = -0.8126625f + RLegXRot;
        this.rightLegB.rotateAngleX = -0.8445741f + RLegXRot;
        this.rightLegC.rotateAngleX = -0.2860688f + RLegXRot;
        this.rightFoot.rotateAngleX = RLegXRot;
        this.leftLegA.rotateAngleX = -0.8126625f + LLegXRot;
        this.leftLegB.rotateAngleX = -0.8445741f + LLegXRot;
        this.leftLegC.rotateAngleX = -0.2860688f + LLegXRot;
        this.leftFoot.rotateAngleX = LLegXRot;
        this.rightArmA.rotateAngleZ = -(MathHelper.cos(ageInTicks * 0.09f) * 0.05f) + 0.05f;
        this.leftArmA.rotateAngleZ = MathHelper.cos(ageInTicks * 0.09f) * 0.05f - 0.05f;
        this.rightArmA.rotateAngleX = LLegXRot;
        this.leftArmA.rotateAngleX = RLegXRot;
        this.rightArmB.rotateAngleZ = 0.3490659f + this.rightArmA.rotateAngleZ;
        this.leftArmB.rotateAngleZ = -0.3490659f + this.leftArmA.rotateAngleZ;
        this.rightArmB.rotateAngleX = 0.2617994f + this.rightArmA.rotateAngleX;
        this.leftArmB.rotateAngleX = 0.2617994f + this.leftArmA.rotateAngleX;
        this.rightArmC.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.leftArmC.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.rightArmC.rotateAngleX = -0.3490659f + this.rightArmA.rotateAngleX;
        this.leftArmC.rotateAngleX = -0.3490659f + this.leftArmA.rotateAngleX;
        this.rightHand.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.leftHand.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.rightHand.rotateAngleX = this.rightArmA.rotateAngleX;
        this.leftHand.rotateAngleX = this.leftArmA.rotateAngleX;
        this.rightFinger1.rotateAngleX = this.rightArmA.rotateAngleX;
        this.rightFinger2.rotateAngleX = this.rightArmA.rotateAngleX;
        this.rightFinger3.rotateAngleX = this.rightArmA.rotateAngleX;
        this.rightFinger4.rotateAngleX = this.rightArmA.rotateAngleX;
        this.rightFinger5.rotateAngleX = this.rightArmA.rotateAngleX;
        this.leftFinger1.rotateAngleX = this.leftArmA.rotateAngleX;
        this.leftFinger2.rotateAngleX = this.leftArmA.rotateAngleX;
        this.leftFinger3.rotateAngleX = this.leftArmA.rotateAngleX;
        this.leftFinger4.rotateAngleX = this.leftArmA.rotateAngleX;
        this.leftFinger5.rotateAngleX = this.leftArmA.rotateAngleX;
        this.rightFinger1.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.rightFinger2.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.rightFinger3.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.rightFinger4.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.rightFinger5.rotateAngleZ = this.rightArmA.rotateAngleZ;
        this.leftFinger1.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.leftFinger2.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.leftFinger3.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.leftFinger4.rotateAngleZ = this.leftArmA.rotateAngleZ;
        this.leftFinger5.rotateAngleZ = this.leftArmA.rotateAngleZ;
    }
}